pipeline:
  conventional_commits:
    image: node:18
    commands:
      - git config --global user.email "moravrav@gmail.com"
      - git config --global user.name "RaviAnand Mohabir"
      - npm i -g standard-version
      - standard-version
      - git tag

branches: main
